Add a grace period between removal from the export indices, and deletion
google/exposure-notifications-server pull request #1162
Opened 2020-11-12 17:19 UTC by jeremyfaller

Fixes #1148

**Release Note**

```release-note
Add a 1 hour grace time between when a file is no longer included in the export file list, and when it's actually deleted.
```

2020-11-13 04:47 UTC, mikehelmick requested changes
the grace period method doesn't work with long batch periods (i.e. 24 hours)
the index file is at best regenerated ever time a batch runs (i.e. every 4 hours in a typical production instance)

we need to guarantee that a file isn't deleted while it is still in the index and this shortens, but doesn't eliminate the race

2020-11-13 18:27 UTC, jeremyfaller commented
> the grace period method doesn't work with long batch periods (i.e. 24 hours)
> the index file is at best regenerated ever time a batch runs (i.e. every 4 hours in a typical production instance)
> 
> we need to guarantee that a file isn't deleted while it is still in the index and this shortens, but doesn't eliminate the race

Sorry. When I read the TF, it looked to me like the indices were being generated every minute. Can you quickly drop a pointer to the section of code I'm apparently misunderstanding.

Thanks, and sorry for the confusion.

2020-11-13 19:19 UTC, mikehelmick commented
> > the grace period method doesn't work with long batch periods (i.e. 24 hours)
> > the index file is at best regenerated ever time a batch runs (i.e. every 4 hours in a typical production instance)
> > we need to guarantee that a file isn't deleted while it is still in the index and this shortens, but doesn't eliminate the race
> 
> Sorry. When I read the TF, it looked to me like the indices were being generated every minute. Can you quickly drop a pointer to the section of code I'm apparently misunderstanding.
> 
> Thanks, and sorry for the confusion.

the job gets a chance to run once a minute, yes, but most of the time has no work to do.

if there are no open batches - then the index file isn't re-written

https://github.com/google/exposure-notifications-server/blob/main/internal/export/worker.go#L79

2020-11-13 19:29 UTC, jeremyfaller commented
Ah, ok, so as I see it, we could take an "easy" way out, and just bump this gracePeriod to be larger than maxexportbatchtime, or actually do a mark and sweep. (I was hoping to avoid that as I'm a little unclear on all the different pieces here, and what the cleanup job can trigger in the main server.) Unless just bumping (and making configurable) this gracePeriod is acceptable, I'll think a bit more about how to mark and sweep.

/hold

2020-11-18 18:39 UTC, jeremyfaller commented
/close

2020-11-18 18:39 UTC, closed without merging